server:
  port: 8106
  servlet:
    context-path: /api/springbootCaching


spring:
  devtools:
    restart:
      enabled: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
